DROP DATABASE IF EXISTS ibt;
CREATE DATABASE ibt;
USE ibt;

CREATE TABLE users(
	id INT AUTO_INCREMENT PRIMARY KEY,
    username VARCHAR(30) NOT NULL,
    password VARCHAR(100) NOT NULL,
	firstname VARCHAR(30) NULL,
	lastname VARCHAR(30) NULL,
	email VARCHAR(50),
	reg_date TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

CREATE TABLE admins(
	id INT AUTO_INCREMENT PRIMARY KEY,
	userId INT,

	FOREIGN KEY (userId)
        REFERENCES users(id)
        ON DELETE CASCADE
);

CREATE TABLE items(
	id INT AUTO_INCREMENT PRIMARY KEY,
	name VARCHAR(30) NULL,
	price int NULL
);

CREATE TABLE userItems(
	id INT AUTO_INCREMENT PRIMARY KEY,
	userId INT NOT NULL,
    itemId INT NOT NULL,
    
    FOREIGN KEY (userId)
        REFERENCES users(id)
        ON DELETE NO ACTION,
        
	FOREIGN KEY (itemId)
        REFERENCES items(id)
        ON DELETE NO ACTION
);